# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20170725_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='image_small',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
    ]
