# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20170726_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='Unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Mainbar'),
        ),
    ]
