# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20170728_1842'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mainbar',
            new_name='Unit',
        ),
    ]
