# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('oauth_type', models.CharField(max_length=128)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('last_visit_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
